version: '3.2'
services:
  postgres:
    image: mariadb:10.7
    container_name: db_bridge
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_PASSWORD=test
      - MYSQL_USER=test
      - MYSQL_DATABASE=test_db
    logging:
      options:
        max-size: 10m
        max-file: '3'
    ports:
      - '3306:3306'

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq_bridge
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1

  redis_db:
    image: redis:alpine
    container_name: redis_bridge
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
