export const SEQUELIZE = 'SEQUELIZE';
export const LIBRARY_REPOSITORY = 'LIBRARY_REPOSITORY';
export const PROFILE_REPOSITORY = 'PROFILE_REPOSITORY';
export const NOTIFICATION_REPOSITORY = 'NOTIFICATION_REPOSITORY';
export const FOLLOWER_REPOSITORY = 'FOLLOWER_REPOSITORY';
