FROM node:16.17.0

ENV NODE_ENV development
ENV ALLOW_CONFIG_MUTATIONS TRUE

RUN wget -O /bin/wait-for-it.sh https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh
RUN chmod +x /bin/wait-for-it.sh

WORKDIR /home/node/src

COPY package*.json ./
RUN yarn
COPY . .

CMD sh -c '/bin/wait-for-it.sh mariadb:3306 --timeout=30 -- yarn db:migrate'
